---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Luke Gregor"
keywords:    "luke gregor, oceanography, carbon, CO2, southern ocean, python, programming"
description: "My research page"
source_link: "https://github.com/luke-gregor"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  blue0:     '#8FD0FF'
  blue1:     '#5FA3D4'
  blue2:     '#2B75AB'
  blue3:     '#13588A'
  blue4:     '#033457'

kramdown:
  auto_ids:  false

